var data = [
    {
        imageUrl: 'https://media.istockphoto.com/photos/dawn-at-sydney-opera-house-australia-picture-id843696704?k=20&m=843696704&s=612x612&w=0&h=hSXOYTkKjSaYYMEEi9JqfODzM8SuSkhRNkk4KMKFEBM=',
        title: 'Sydeny Opera House, Australia',
        desc: "The Sydney Opera House is a multi-venue performing arts centre on Sydney Harbour located in Sydney, New South Wales, Australia. It is one of the 20th century's most famous and distinctive buildings. Designed by Danish architect Jørn Utzon, but completed by an Australian architectural team headed by Peter Hall, the building was formally opened on 20 October 1973 after a gestation beginning with Utzon's 1957 selection as winner of an international design competition. The Government of New South Wales, led by the premier, Joseph Cahill, authorised work to begin in 1958 with Utzon directing construction. The government's decision to build Utzon's design is often overshadowed by circumstances that followed, including cost and scheduling overruns as well as the architect's ultimate resignation. The building and its surrounds occupy the whole of Bennelong Point on Sydney Harbour, between Sydney Cove and Farm Cove, adjacent to the Sydney central business district and the Royal Botanic Gardens, and close by the Sydney Harbour Bridge.",
        wikiLink: 'https://en.wikipedia.org/wiki/Sydney_Opera_House'
    },
    {
        imageUrl: 'https://pbs.twimg.com/media/EmEYg46XIAAnd7T.jpg',
        title: 'Pyramids, Giza, Egypt',
        desc: 'The Egyptian pyramids are ancient masonry structures located in Egypt. Sources cite at least 118 identified Egyptian pyramids.Most were built as tombs for the countrys pharaohs and their consorts during the Old and Middle Kingdom periods.The earliest known Egyptian pyramids are found at Saqqara, northwest of Memphis, although at least one step-pyramid-like structure has been found at Saqqara, dating to the First Dynasty: Mastaba 3808, which has been attributed to the reign of Pharaoh Anedjib, with inscriptions, and other archaeological remains of the period, suggesting there may have been others. The otherwise earliest among these is the Pyramid of Djoser built c. 2630–2610 BCE during the Third Dynasty.  This pyramid and its surrounding complex are generally considered to be the worlds oldest monumental structures constructed of dressed masonry.  The most famous Egyptian pyramids are those found at Giza, on the outskirts of Cairo. Several of the Giza pyramids are  counted among the largest structures ever built.The Pyramid of Khufu is the largest Egyptian pyramid.  It is the only one of the Seven Wonders of the Ancient World still in existence; this is despite being the oldest   wonder by about 2,000 years.',
        wikiLink: 'https://en.wikipedia.org/wiki/Egyptian_pyramids',
    },
    {
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1b/The_Great_Wall_of_China_-_Badaling.jpg',
        title: ' Great wall, China',
        desc: 'The Great Wall of China (traditional Chinese: 萬里長城; simplified Chinese: 万里长城; pinyin: Wànlǐ Chángchéng) is a series of fortifications that were built across the historical northern borders of ancient Chinese states and Imperial China as protection against various nomadic groups from the Eurasian Steppe. Several walls were built from as early as the 7th century BC, with selective stretches later joined together by Qin Shi Huang (220–206 BC), the first emperor of China. Little of the Qin wall remains.Later on, many successive dynasties built and maintained multiple stretches of border walls. The most well-known sections of the wall were built by the Ming dynasty (1368–1644). Apart from defense, other purposes of the Great Wall have included border controls, allowing the imposition of duties on goods transported along the Silk Road, regulation or encouragement of trade and the control of immigration and emigration. Furthermore, the defensive characteristics of the Great Wall were enhanced by the construction of watchtowers, troop barracks, garrison stations, signaling capabilities through the means of smoke or fire, and the fact that the path of the Great Wall also served as a transportation corridor. The frontier walls built by different dynasties have multiple courses. Collectively, they stretch from Liaodong in the east to Lop Lake in the west, from the present-day Sino–Russian border in the north to Tao River (Taohe) in the south; along an arc that roughly delineates the edge of the Mongolian steppe; spanning over 20,000 km (12,000 mi) in total.Today, the defensive system of the Great Wall is generally recognized as one of the most impressive architectural feats in history.',
        wikiLink: 'https://en.wikipedia.org/wiki/Great_Wall_of_China'
    },
    {
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/The_Leaning_Tower_of_Pisa_SB.jpeg/220px-The_Leaning_Tower_of_Pisa_SB.jpeg',
        title: 'Leaning Tower of Pisa, Italy',
        desc: "The Leaning Tower of Pisa (Italian: torre pendente di Pisa), or simply the Tower of Pisa, is the campanile, or freestanding bell tower, of the cathedral of the Italian city of Pisa, known worldwide for its nearly four-degree lean, theresult of an unstable foundation. The tower is situated behind the Pisa Cathedral and is the third-oldest structure in the city's Cathedral Square (Piazza del Duomo), after the cathedral and the Pisa Baptistry. The height of the tower is 55.86 metres (183.27 feet) from the ground on the low side and 56.67 metres (185.93 feet) on the high side. The width of the walls at the base is 2.44 m (8 ft 0.06 in). Its weight is estimated at 14,500 metric tons (16,000 short tons). The tower has 296 or 294 steps; the seventh floor has two fewer steps on the north-facing staircase. The tower began to lean during construction in the 12th century, due to soft ground which could not properly support the structure's weight, and it worsened through the completion of construction in the 14th century. By 1990, the tilt had reached 5.5 degrees. The structure was stabilized by remedial work between 1993 and 2001, which reduced the tilt to 3.97 degrees. ",
        wikiLink: 'https://en.wikipedia.org/wiki/Leaning_Tower_of_Pisa'
    },
    {
        imageUrl : 'https://i.pinimg.com/originals/0a/ee/68/0aee68e5e233cad0c948e3789d08f085.jpg',
        title : 'Eiffel Tower, Paris, France',
        desc : 'The Eiffel Tower French: tour Eiffel is a wrought-iron lattice tower on the Champ de Mars in Paris, France. It is named after the engineer Gustave Eiffel, whose company designed and built the tower Locally nicknamed La dame de fer (French for Iron Lady), it was constructed from 1887 to 1889 as the entrance to the 1889 Worlds Fair and was initially criticised by some of Frances leading artists and intellectuals for its design, but it has become a global cultural icon of France and one of the most recognisable structures in the world.  The Eiffel Tower is the most-visited paid monument in the world; 6.91 million people ascended it in 2015. The tower is 324 metres (1,063 ft) tall, about the same height as an 81-storey building, and the tallest structure in Paris. Its base is  square, measuring 125 metres (410 ft) on each side. During its construction, the Eiffel Tower surpassed the Washington Monument to become  the tallest man-made structure in the world, a title it held for 41 years until the Chrysler Building in New York City was finished in  1930. It was the first structure in the world to surpass both the 200 meter and 300 meter mark in height. Due to the addition of a  broadcasting aerial at the top of the tower in 1957, it is now taller than the Chrysler Building by 5.2 metres (17 ft). Excluding  transmitters, the Eiffel Tower is the second tallest free-standing structure in France after the Millau Viaduct. The tower has three levels for visitors, with restaurants on the first and second levels. The top levels upper platform is 276 m  (906 ft) above the ground – the highest observation deck accessible to the public in the European Union. Tickets can be purchased to  ascend by stairs or lift to the first and second levels. The climb from ground level to the first level is over 300 steps, as is the  climb from the first level to the second. Although there is a staircase to the top level, it is usually accessible only by lift.',
        wikiLink: 'https://en.wikipedia.org/wiki/Eiffel_Tower',
    },
    {
        imageUrl: 'https://i.pinimg.com/564x/1b/8a/c4/1b8ac485272d6dec5bedf554013f83cd.jpg',
        title: 'Mont Saint-Michel, Normandy, France',
        desc: "Le Mont-Saint-Michel Norman: Mont Saint Miché, English: Saint Michael's Mount) is a tidal island and mainland commune in Normandy, France. The island lies approximately one kilometre (0.6 miles) off the country's north-western coast, at the mouth of the Couesnon River near Avranches and is 7 hectares (17 acres) in area. The mainland part of the commune is 393 hectares (971 acres) in area so that the total surface of the commune is 400 hectares (988 acres). As of 2017, the island had a population of 30. The commune's position—on an island just a few hundred metres from land—made it accessible at low tide to the many pilgrims to its abbey, but defensible as an incoming tide stranded, drove off, or drowned would-be assailants. The island remained unconquered during the Hundred Years' War; a small garrison fended off a full attack by the English in 1433. Louis XI recognised the reverse benefits of its natural defence and turned it into a prison. The abbey was used regularly as a prison during the Ancien Régime.",
        wikiLink: 'https://en.wikipedia.org/wiki/Mont-Saint-Michel'
    },
    {
        imageUrl: 'https://luxeadventuretraveler.com/wp-content/uploads/2012/12/Luxe-Adventure-Traveler-Dubai-Burj-Khalifa-6.jpg',
        title: 'Burj Khalifa, Dubai, UAE',
        desc: "Construction of the Burj Khalifa began in 2004, with the exterior completed five years later in 2009. The primary structure is reinforced concrete and some of the structural steel for the building originated from the Palace of the Republic in East Berlin, the former East German parliament. The building was opened in 2010 as part of a new development called Downtown Dubai. It is designed to be the centrepiece of large-scale, mixed-use development. The decision to construct the building is based on the government's decision to diversify from an oil-based economy, and for Dubai to gain international recognition. The building was originally named Burj Dubai but was renamed in honour of the ruler of Abu Dhabi and president of the United Arab Emirates, Khalifa bin Zayed Al Nahyan; Abu Dhabi and the UAE government lent Dubai money to pay its debts. The building broke numerous height records, including its designation as the tallest building in the world.",
        wikiLink: 'https://en.wikipedia.org/wiki/Burj_Khalifa'
    },
    {
        imageUrl:'https://res.cloudinary.com/odysseytraveller/image/fetch/f_auto,q_auto,dpr_auto,r_4,w_765,h_1147.5,c_limit/https://cdn.odysseytraveller.com/app/uploads/2018/02/Taj-Mahal-India-iStock-483076881.jpg',
        title: 'Taj Mahal, India',
        desc: "The Taj Mahal attracts a large number of tourists. UNESCO documented more than 2 million visitors in 2001, which had increased to about 7–8 million in 2014. A two-tier pricing system is in place, with a significantly lower entrance fee for Indian citizens and a more expensive one for foreigners. In 2018, the fee for Indian citizens was 50 INR, for foreign tourists 1,100 INR. Most tourists visit in the cooler months of October, November and February. Polluting traffic is not allowed near the complex and tourists must either walk from parking areas or catch an electric bus. The Khawasspuras (northern courtyards) are currently being restored for use as a new visitor centre. In 2019, in order to address overtourism, the site instituted fines for visitors who stayed longer than three hours. The grounds are open from 06:00 to 19:00 weekdays, except for Friday when the complex is open for prayers at the mosque between 12:00 and 14:00. The complex is open for night viewing on the day of the full moon and two days before and after, excluding Fridays and the month of Ramadan.",
        wikiLink: 'https://en.wikipedia.org/wiki/Taj_Mahal'
    },
    {
        imageUrl: 'https://i.pinimg.com/originals/98/0d/5c/980d5ca844b35f565a6dba2d67cbacde.jpg',
        title: 'Statue of Liberty, USA',
        desc: "The statue is situated in Upper New York Bay on Liberty Island south of Ellis Island, which together comprise the Statue of Liberty National Monument. Both islands were ceded by New York to the federal government in 1800. As agreed in an 1834 compact between New York and New Jersey that set the state border at the bay's midpoint, the original islands remain New York territory though located on the New Jersey side of the state line. Liberty Island is one of the islands that are part of the borough of Manhattan in New York. Land created by reclamation added to the 2.3-acre (0.93 ha) original island at Ellis Island is New Jersey territory. No charge is made for entrance to the national monument, but there is a cost for the ferry service that all visitors must use, as private boats may not dock at the island. A concession was granted in 2007 to Statue Cruises to operate the transportation and ticketing facilities, replacing Circle Line, which had operated the service since 1953. The ferries, which depart from Liberty State Park in Jersey City and the Battery in Lower Manhattan, also stop at Ellis Island when it is open to the public, making a combined trip possible. All ferry riders are subject to security screening, similar to airport procedures, prior to boarding",
        wikiLink: 'https://en.wikipedia.org/wiki/Statue_of_Liberty'
    },
    {
        imageUrl: 'https://image.posterlounge.com/images/l/1891828.jpg',
        title: 'Machu Picchu, Peru',
        desc: "Machu Picchu is both a cultural and natural UNESCO World Heritage Site. Since its discovery in 1911, growing numbers of tourists have visited the site each year, with numbers exceeding 1.4 million in 2017. As Peru's most visited tourist attraction and major revenue generator, it is continually exposed to economic and commercial forces. In the late 1990s, the Peruvian government granted concessions to allow the construction of a cable car and a luxury hotel, including a tourist complex with boutiques and restaurants and a bridge to the site. Many people protested the plans, including Peruvians and foreign scientists, saying that more visitors would pose a physical burden on the ruins. In 2018, plans were restarted to again construct a cable car to encourage Peruvians to visit Machu Picchu and boost domestic tourism. A no-fly zone exists above the area. UNESCO is considering putting Machu Picchu on its List of World Heritage in Danger.",
        wikiLink: 'https://en.wikipedia.org/wiki/Machu_Picchu'
    },
    {
        imageUrl: 'https://www.kevinandamanda.com/wp-content/uploads/2020/03/angkor-wat-temple-cambodia-01-720x1080.jpg',
        title: 'Angkor Wat, Siem Reap, Cambodia',
        desc: "Angkor Wat, located in northwest Cambodia, is the largest religious structure (temple complex) in the world by land area, measuring 162.6 hectares (401+3⁄4 acres). At the centre of the temple stands a quincunx of four towers surrounding a central spire that rises to a height of 65 m (213 ft) above the ground. The temple has three rectangular galleries, each raised above the next. It lies within an outer wall 3.6 kilometres (2+1⁄4 miles) long and a moat more than five kilometres (three miles) long. The temple was built at the behest of Suryavarman II in the early 12th century in Yaśodharapura (យសោធរបុរៈ, present-day Angkor), the capital of the Khmer Empire, as the state temple for the empire. Originally constructed as a personal mausoleum for Suryavarman, dedicated to the Hindu god Vishnu in the early 12th century, it was converted to a Buddhist temple towards the end of the 12th century.",
        wikiLink: 'https://en.wikipedia.org/wiki/Angkor_Wat'
    },
    {
        imageUrl: 'https://thumbs.dreamstime.com/z/abraham-lincoln-face-mount-rushmore-south-dakota-usa-mount-rushmore-national-memorial-sculpture-carved-137688002.jpg',
        title: 'Mount Rushmore, Keystone, South Dakota',
        desc: "Mount Rushmore National Memorial is centered on a colossal sculpture carved into the granite face of Mount Rushmore (Lakota: Tȟuŋkášila Šákpe, or Six Grandfathers) in the Black Hills near Keystone, South Dakota. Sculptor Gutzon Borglum created the sculpture's design and oversaw the project's execution from 1927 to 1941 with the help of his son, Lincoln Borglum. The sculpture features the 60-foot (18 m) heads of Presidents George Washington (1732–1799), Thomas Jefferson (1743–1826), Theodore Roosevelt (1858–1919) and Abraham Lincoln (1809–1865), as recommended by Borglum. The four presidents were chosen to represent the nation's birth, growth, development and preservation, respectively. The memorial park covers 1,278 acres (2.00 sq mi; 5.17 km2) and the actual mountain has an elevation of 5,725 feet (1,745 m) above sea level.",
        wikiLink: 'https://en.wikipedia.org/wiki/Mount_Rushmore'
    },
];
function logging(){

    var index = parseInt(localStorage.getItem('index'));
    document.getElementById('imageUrl').src = data[index].imageUrl;
    document.getElementById('title').innerHTML = data[index].title;
    document.getElementById('desc').innerHTML = data[index].desc;
    document.getElementById('wikiLink').href = data[index].wikiLink;

}
